<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Jellyfin.Plugin.TorrentSearch</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.TorrentSearch</RootNamespace>
    <Version>1.0.2</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <InformationalVersion>1.0.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="MonoTorrent" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.6.4" />
    <PackageReference Include="qBittorrent.Client" Version="1.0.18206.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\config.html" />
    <EmbeddedResource Include="Configuration\config.css" />
  </ItemGroup>

</Project>
